### PR TITLE
requirements: Update all requirements

### PR DESCRIPTION
**Pull request by Bjwebb**
I still need to check this manually. I think the width/wrapping of the validation table might be slightly broken.

### CODE REVIEW

**Comment by Bjwebb** [comment]
I've checked the styling of the validation table.

Current table:
Screenshot from 2021-04-09 11-13-00

Table after this PR:
Screenshot from 2021-04-09 11-11-41

This is not too bad, so I suggest merging this to make sure requirements are up to date. We can then make a new issue/pr if we want to look into changing the styling back.

**Review by rhiaro — APPROVED** [review]
That looks fine to me

**Comment by kd-ods** [comment]
Formatting looks good to me too, @Bjwebb.

**Comment by Bjwebb** [comment]
Great, thanks. I'll avoid the Friday afternoon deploy, so will do this on Tuesday morning.

**Comment by Bjwebb** [comment]
After all that the table is formatted like it was before! Must be something with live vs dev, rather than what version of the code is running.

**Pull request merged**
