### PR TITLE
WIP Make prettier Stats

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
prettier-stats

@rhiaro @ScatteredInk @kd-ods Comments?

**Comment by Bjwebb** [comment]
Looks fine to me.

**Comment by kd-ods** [comment]
I'd prefer to leave all the 'Statistics' in a single section, rather than splitting them out into 'Statistics: Entity...'. 'Statistics: People...' and so on. (The reason being that we then have a proliferation of sections at the same level of importance as - e.g. - 'Validation errors')

Subheadings within a single 'Statistics' section would do for now. And could we rename the Statistics section to 'Content review' for now, too? It's a bit more friendly and meaningful.

(The next BODS CoVE sprint will be a chance to work on all of the aspects of presentation.)

**Comment by odscjames** [comment]
I have had a first go at this in #28

**Comment by odscjames** [comment]
From #28:

**Comment by kd-ods** [comment]
Looks good - thanks, @odscjames!

**Comment by odscjames** [comment]
Closing - think all the work was done in #28

**Pull request closed without merging**
